language: android
android:
    components:
        - build-tools-20.0.0
        - android-20
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
    licenses:
        - '.+'