language: android
jdk: openjdk7
env:
    matrix:
        - ANDROID_TARGET=android-20  ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
        - ANDROID_TARGET=android-8  ANDROID_ABI=armeabi

android:
    components:
        - build-tools-20.0.0
        - android-20
        - extra-android-support
        - extra-google-m2repository
        - extra-android-m2repository
    licenses:
        - '.+'

branches:
    except:
        - gh-pages

before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

#script:
#    - ./gradlew clean assemble check